### PR TITLE
Adding "--expand" option

### PR DESCRIPTION
**Pull request by willjacobs**
Added option to support the '--expand' CLI switch - this expanded JSON format is used for integration with Atlassian Jira for automated test result integration.

### CODE REVIEW

**Comment by dnwe** [comment]
@samueltbrown this would also be helpful for the Jenkins cucumber results plugin. Are you currently accepting PRs?

It probably also needs a README.md update referencing the [docs](https://www.relishapp.com/cucumber/cucumber/docs/gherkin/scenario-outlines-expand-option)

**Comment by samueltbrown** [comment]
@dnwe We are accepting pull requests but I have not built the gradle packages in years.  @viphe Are you still able to push new versions of the plugin to bintray?

**Comment by viphe** [comment]
I should be able to. I'll try to review pending items ASAP.

**Comment by viphe** [comment]
@willjacobs 
I accepted this pull request a little bit quickly.
The proposed pull request didn't include the any extension to the Gradle DSL (and any of the glue code beween that and the command line).

But more important, my own tests would tend to show that Cucmber for VM does not support `--expand`. Although it is documented for the Ruby version, it doesn't seem to be documented for the JVM version ([here](https://cucumber.io/docs/reference/jvm#list-configuration-options)).

I moved your commits and mine to https://github.com/samueltbrown/gradle-cucumber-plugin/tree/support-expand-option for now.

Did you test before? Do you know if the expand option is supported by Cucumber for JVM and in what form (it could be a plugin I didn't see)?

**Pull request merged**
